import { Person } from "../lib/types/persons.types";

export const personDbs: Array<Person> = [
  {
    "firstName": "Brandon",
    "lastName": "Morris",
    "age": 83,
    "phone": "+1-332-555-1821",
    "street": "Northern Boulevard",
    "houseNumber": "533",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Daniel",
    "lastName": "Sanchez",
    "age": 53,
    "phone": "+1-212-555-4820",
    "street": "Northern Boulevard",
    "houseNumber": "2124",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Pamela",
    "lastName": "Lee",
    "age": 58,
    "phone": "+1-929-555-7268",
    "street": "York Avenue",
    "houseNumber": "4308",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Kevin",
    "lastName": "Taylor",
    "age": 21,
    "phone": "+1-347-555-6736",
    "street": "Park Avenue",
    "houseNumber": "6676",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Sarah",
    "lastName": "Anderson",
    "age": 32,
    "phone": "+1-646-555-9555",
    "street": "West End Avenue",
    "houseNumber": "5837",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Michael",
    "lastName": "Diaz",
    "age": 21,
    "phone": "+1-212-555-9523",
    "street": "Northern Boulevard",
    "houseNumber": "167",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Angela",
    "lastName": "Evans",
    "age": 21,
    "phone": "+1-718-555-1882",
    "street": "Atlantic Avenue",
    "houseNumber": "2159",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Shirley",
    "lastName": "Bennett",
    "age": 28,
    "phone": "+1-929-555-8097",
    "street": "23rd Street",
    "houseNumber": "4680",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Emily",
    "lastName": "Williams",
    "age": 24,
    "phone": "+1-347-555-7861",
    "street": "3rd Avenue",
    "houseNumber": "8980",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Jessica",
    "lastName": "Rivera",
    "age": 23,
    "phone": "+1-347-555-8916",
    "street": "Flatbush Avenue",
    "houseNumber": "7583",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Karen",
    "lastName": "Cook",
    "age": 69,
    "phone": "+1-718-555-2811",
    "street": "Fordham Road",
    "houseNumber": "7071",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Emma",
    "lastName": "Perez",
    "age": 36,
    "phone": "+1-718-555-8291",
    "street": "8th Avenue",
    "houseNumber": "5746",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Scott",
    "lastName": "Johnson",
    "age": 52,
    "phone": "+1-917-555-9776",
    "street": "34th Street",
    "houseNumber": "944",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Emily",
    "lastName": "Wood",
    "age": 83,
    "phone": "+1-718-555-4281",
    "street": "York Avenue",
    "houseNumber": "7792",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Laura",
    "lastName": "Davis",
    "age": 32,
    "phone": "+1-332-555-8769",
    "street": "York Avenue",
    "houseNumber": "8146",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Edward",
    "lastName": "Rogers",
    "age": 44,
    "phone": "+1-718-555-4505",
    "street": "42nd Street",
    "houseNumber": "6303",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Christopher",
    "lastName": "Davis",
    "age": 61,
    "phone": "+1-332-555-7924",
    "street": "Richmond Terrace",
    "houseNumber": "9339",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Amy",
    "lastName": "Myers",
    "age": 83,
    "phone": "+1-718-555-4867",
    "street": "Richmond Terrace",
    "houseNumber": "1172",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Donald",
    "lastName": "Hill",
    "age": 30,
    "phone": "+1-347-555-5025",
    "street": "York Avenue",
    "houseNumber": "9492",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Timothy",
    "lastName": "Garcia",
    "age": 43,
    "phone": "+1-917-555-8726",
    "street": "3rd Avenue",
    "houseNumber": "3379",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Timothy",
    "lastName": "Stewart",
    "age": 54,
    "phone": "+1-917-555-7671",
    "street": "3rd Avenue",
    "houseNumber": "9557",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Dennis",
    "lastName": "Brown",
    "age": 73,
    "phone": "+1-347-555-5278",
    "street": "42nd Street",
    "houseNumber": "2158",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Carol",
    "lastName": "Perez",
    "age": 58,
    "phone": "+1-929-555-6214",
    "street": "Broadway",
    "houseNumber": "7151",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Sharon",
    "lastName": "King",
    "age": 26,
    "phone": "+1-332-555-4536",
    "street": "6th Avenue",
    "houseNumber": "3296",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Ryan",
    "lastName": "Scott",
    "age": 23,
    "phone": "+1-212-555-3435",
    "street": "42nd Street",
    "houseNumber": "1094",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Nicole",
    "lastName": "Nelson",
    "age": 21,
    "phone": "+1-929-555-4405",
    "street": "14th Street",
    "houseNumber": "2449",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Stephanie",
    "lastName": "Carter",
    "age": 20,
    "phone": "+1-646-555-7820",
    "street": "Atlantic Avenue",
    "houseNumber": "3582",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Angela",
    "lastName": "Flores",
    "age": 82,
    "phone": "+1-347-555-2441",
    "street": "Northern Boulevard",
    "houseNumber": "7539",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Lauren",
    "lastName": "Alvarez",
    "age": 55,
    "phone": "+1-332-555-5297",
    "street": "Park Avenue",
    "houseNumber": "1637",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Kathleen",
    "lastName": "Moore",
    "age": 20,
    "phone": "+1-917-555-5691",
    "street": "2nd Avenue",
    "houseNumber": "5448",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Margaret",
    "lastName": "Price",
    "age": 24,
    "phone": "+1-347-555-1100",
    "street": "Roosevelt Avenue",
    "houseNumber": "4350",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Thomas",
    "lastName": "Jones",
    "age": 25,
    "phone": "+1-212-555-4964",
    "street": "Hylan Boulevard",
    "houseNumber": "406",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Brandon",
    "lastName": "Gutierrez",
    "age": 43,
    "phone": "+1-646-555-3981",
    "street": "10th Avenue",
    "houseNumber": "7810",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Robert",
    "lastName": "Long",
    "age": 61,
    "phone": "+1-646-555-9931",
    "street": "14th Street",
    "houseNumber": "209",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Anna",
    "lastName": "Wilson",
    "age": 19,
    "phone": "+1-917-555-8496",
    "street": "Hylan Boulevard",
    "houseNumber": "8937",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Dennis",
    "lastName": "Cook",
    "age": 64,
    "phone": "+1-718-555-5422",
    "street": "Houston Street",
    "houseNumber": "4749",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Shirley",
    "lastName": "Myers",
    "age": 42,
    "phone": "+1-646-555-2300",
    "street": "Fordham Road",
    "houseNumber": "3332",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Karen",
    "lastName": "Perez",
    "age": 22,
    "phone": "+1-332-555-1551",
    "street": "9th Avenue",
    "houseNumber": "6905",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Jerry",
    "lastName": "Rivera",
    "age": 74,
    "phone": "+1-718-555-3638",
    "street": "7th Avenue",
    "houseNumber": "2796",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Amy",
    "lastName": "Morris",
    "age": 54,
    "phone": "+1-718-555-1023",
    "street": "5th Avenue",
    "houseNumber": "7831",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Michael",
    "lastName": "Richardson",
    "age": 31,
    "phone": "+1-917-555-6438",
    "street": "57th Street",
    "houseNumber": "2114",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Gary",
    "lastName": "Adams",
    "age": 60,
    "phone": "+1-332-555-8595",
    "street": "Main Street",
    "houseNumber": "6434",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Daniel",
    "lastName": "Stewart",
    "age": 59,
    "phone": "+1-212-555-9437",
    "street": "Hylan Boulevard",
    "houseNumber": "9609",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Mia",
    "lastName": "Reed",
    "age": 57,
    "phone": "+1-347-555-7718",
    "street": "Hylan Boulevard",
    "houseNumber": "58",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Patricia",
    "lastName": "Lee",
    "age": 40,
    "phone": "+1-212-555-9737",
    "street": "Grand Concourse",
    "houseNumber": "9299",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Sharon",
    "lastName": "Castillo",
    "age": 23,
    "phone": "+1-718-555-6566",
    "street": "Houston Street",
    "houseNumber": "1772",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Samuel",
    "lastName": "Jones",
    "age": 85,
    "phone": "+1-718-555-7418",
    "street": "Roosevelt Avenue",
    "houseNumber": "608",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Elizabeth",
    "lastName": "Miller",
    "age": 45,
    "phone": "+1-332-555-9422",
    "street": "York Avenue",
    "houseNumber": "331",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Rachel",
    "lastName": "Castillo",
    "age": 27,
    "phone": "+1-929-555-7839",
    "street": "York Avenue",
    "houseNumber": "8192",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Joseph",
    "lastName": "Wilson",
    "age": 33,
    "phone": "+1-917-555-2031",
    "street": "9th Avenue",
    "houseNumber": "8632",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Steven",
    "lastName": "Richardson",
    "age": 66,
    "phone": "+1-718-555-5343",
    "street": "West End Avenue",
    "houseNumber": "4765",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Jacob",
    "lastName": "Davis",
    "age": 50,
    "phone": "+1-917-555-4994",
    "street": "5th Avenue",
    "houseNumber": "4148",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Daniel",
    "lastName": "Bennett",
    "age": 21,
    "phone": "+1-347-555-6780",
    "street": "Richmond Terrace",
    "houseNumber": "5634",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Timothy",
    "lastName": "Richardson",
    "age": 19,
    "phone": "+1-332-555-3744",
    "street": "5th Avenue",
    "houseNumber": "3653",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Susan",
    "lastName": "James",
    "age": 83,
    "phone": "+1-212-555-3951",
    "street": "Atlantic Avenue",
    "houseNumber": "7071",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Ronald",
    "lastName": "Kim",
    "age": 41,
    "phone": "+1-718-555-2845",
    "street": "Madison Avenue",
    "houseNumber": "7028",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Nancy",
    "lastName": "Foster",
    "age": 33,
    "phone": "+1-212-555-6764",
    "street": "86th Street",
    "houseNumber": "8196",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Nicole",
    "lastName": "Ortiz",
    "age": 57,
    "phone": "+1-332-555-4653",
    "street": "34th Street",
    "houseNumber": "1880",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Mary",
    "lastName": "Nguyen",
    "age": 20,
    "phone": "+1-718-555-5934",
    "street": "Lexington Avenue",
    "houseNumber": "7851",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Amanda",
    "lastName": "Jimenez",
    "age": 45,
    "phone": "+1-718-555-3936",
    "street": "Fordham Road",
    "houseNumber": "9599",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Thomas",
    "lastName": "Flores",
    "age": 60,
    "phone": "+1-646-555-2536",
    "street": "1st Avenue",
    "houseNumber": "6658",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Raymond",
    "lastName": "Taylor",
    "age": 75,
    "phone": "+1-929-555-5427",
    "street": "Fordham Road",
    "houseNumber": "9481",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Jerry",
    "lastName": "Nelson",
    "age": 65,
    "phone": "+1-332-555-5345",
    "street": "Houston Street",
    "houseNumber": "4310",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Sharon",
    "lastName": "Reed",
    "age": 81,
    "phone": "+1-929-555-7185",
    "street": "1st Avenue",
    "houseNumber": "8110",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Samantha",
    "lastName": "Rodriguez",
    "age": 69,
    "phone": "+1-212-555-3559",
    "street": "Roosevelt Avenue",
    "houseNumber": "4407",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Joshua",
    "lastName": "Rivera",
    "age": 56,
    "phone": "+1-917-555-2218",
    "street": "2nd Avenue",
    "houseNumber": "7037",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Timothy",
    "lastName": "Martin",
    "age": 63,
    "phone": "+1-347-555-5727",
    "street": "Prince Street",
    "houseNumber": "5776",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Kimberly",
    "lastName": "Myers",
    "age": 75,
    "phone": "+1-646-555-6390",
    "street": "3rd Avenue",
    "houseNumber": "8370",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Anthony",
    "lastName": "Miller",
    "age": 24,
    "phone": "+1-718-555-5654",
    "street": "Wall Street",
    "houseNumber": "4245",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Tyler",
    "lastName": "Parker",
    "age": 85,
    "phone": "+1-917-555-7725",
    "street": "42nd Street",
    "houseNumber": "1821",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Rebecca",
    "lastName": "Robinson",
    "age": 50,
    "phone": "+1-929-555-1366",
    "street": "Prince Street",
    "houseNumber": "7461",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Nancy",
    "lastName": "Allen",
    "age": 57,
    "phone": "+1-917-555-6178",
    "street": "Atlantic Avenue",
    "houseNumber": "9059",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Stephen",
    "lastName": "Sanchez",
    "age": 69,
    "phone": "+1-917-555-8956",
    "street": "Columbus Avenue",
    "houseNumber": "9416",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Olivia",
    "lastName": "Robinson",
    "age": 41,
    "phone": "+1-718-555-7934",
    "street": "Atlantic Avenue",
    "houseNumber": "3183",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Michael",
    "lastName": "Peterson",
    "age": 51,
    "phone": "+1-917-555-6118",
    "street": "Houston Street",
    "houseNumber": "4232",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Nancy",
    "lastName": "Wilson",
    "age": 40,
    "phone": "+1-929-555-2857",
    "street": "Park Avenue",
    "houseNumber": "804",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Deborah",
    "lastName": "Sanchez",
    "age": 67,
    "phone": "+1-929-555-9690",
    "street": "Spring Street",
    "houseNumber": "7458",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Ryan",
    "lastName": "Young",
    "age": 42,
    "phone": "+1-332-555-1649",
    "street": "10th Avenue",
    "houseNumber": "3794",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Robert",
    "lastName": "Price",
    "age": 22,
    "phone": "+1-347-555-2930",
    "street": "5th Avenue",
    "houseNumber": "9337",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Jack",
    "lastName": "Thompson",
    "age": 62,
    "phone": "+1-718-555-6567",
    "street": "57th Street",
    "houseNumber": "9428",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Andrew",
    "lastName": "Mitchell",
    "age": 78,
    "phone": "+1-929-555-3950",
    "street": "14th Street",
    "houseNumber": "8010",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "William",
    "lastName": "Jones",
    "age": 79,
    "phone": "+1-212-555-9485",
    "street": "Madison Avenue",
    "houseNumber": "7672",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Jacob",
    "lastName": "Stewart",
    "age": 35,
    "phone": "+1-212-555-9916",
    "street": "8th Avenue",
    "houseNumber": "7437",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Karen",
    "lastName": "Smith",
    "age": 60,
    "phone": "+1-718-555-2062",
    "street": "Wall Street",
    "houseNumber": "5727",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Amy",
    "lastName": "Kelly",
    "age": 56,
    "phone": "+1-929-555-7291",
    "street": "86th Street",
    "houseNumber": "6136",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Ronald",
    "lastName": "Wood",
    "age": 84,
    "phone": "+1-347-555-6747",
    "street": "Broadway",
    "houseNumber": "6884",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Susan",
    "lastName": "Gomez",
    "age": 20,
    "phone": "+1-332-555-6923",
    "street": "Grand Concourse",
    "houseNumber": "8547",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Charles",
    "lastName": "Allen",
    "age": 82,
    "phone": "+1-332-555-8236",
    "street": "Park Avenue",
    "houseNumber": "3428",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "Patrick",
    "lastName": "Chavez",
    "age": 31,
    "phone": "+1-718-555-3002",
    "street": "2nd Avenue",
    "houseNumber": "8806",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Mary",
    "lastName": "Phillips",
    "age": 36,
    "phone": "+1-917-555-7409",
    "street": "9th Avenue",
    "houseNumber": "8139",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Emma",
    "lastName": "Phillips",
    "age": 21,
    "phone": "+1-332-555-6125",
    "street": "Fordham Road",
    "houseNumber": "1988",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Brian",
    "lastName": "Miller",
    "age": 71,
    "phone": "+1-917-555-4623",
    "street": "York Avenue",
    "houseNumber": "4464",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Gary",
    "lastName": "Foster",
    "age": 65,
    "phone": "+1-332-555-9246",
    "street": "14th Street",
    "houseNumber": "8456",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "James",
    "lastName": "Smith",
    "age": 78,
    "phone": "+1-646-555-1675",
    "street": "5th Avenue",
    "houseNumber": "4379",
    "state": "NY",
    "city": "Bronx",
    "country": "USA"
  },
  {
    "firstName": "Linda",
    "lastName": "Phillips",
    "age": 53,
    "phone": "+1-347-555-2967",
    "street": "8th Avenue",
    "houseNumber": "398",
    "state": "NY",
    "city": "Queens",
    "country": "USA"
  },
  {
    "firstName": "James",
    "lastName": "Hall",
    "age": 40,
    "phone": "+1-718-555-4281",
    "street": "23rd Street",
    "houseNumber": "1785",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  },
  {
    "firstName": "Paul",
    "lastName": "Garcia",
    "age": 32,
    "phone": "+1-347-555-8430",
    "street": "42nd Street",
    "houseNumber": "4671",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Sharon",
    "lastName": "Wood",
    "age": 59,
    "phone": "+1-332-555-7700",
    "street": "Bedford Avenue",
    "houseNumber": "2247",
    "state": "NY",
    "city": "Staten Island",
    "country": "USA"
  },
  {
    "firstName": "Gary",
    "lastName": "Johnson",
    "age": 78,
    "phone": "+1-929-555-1700",
    "street": "42nd Street",
    "houseNumber": "3916",
    "state": "NY",
    "city": "Brooklyn",
    "country": "USA"
  },
  {
    "firstName": "Emily",
    "lastName": "Ruiz",
    "age": 39,
    "phone": "+1-332-555-8167",
    "street": "8th Avenue",
    "houseNumber": "5679",
    "state": "NY",
    "city": "New York",
    "country": "USA"
  }
]